menu:
  Home:
    url: '/'
  Articles:
    url: '/articles'
    has_slug: true
  About:
    url: '/about'
  Socials:
    url: null
    submenu:
      X:
        url: 'https://x.com'
        external: true
      Github:
        url: 'https://github.com'
        external: true